server:
  port: 80


#ribbon 需要eureka客户端做媒介实现
eureka:
  client:                                                 #客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://localhost:7001/eureka           #注册到哪个服务中心
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka           #注册到哪个服务中心
  instance:
    instance-id: microservicecloud-consumer80
    prefer-ip-address: true                               #访问路径可以显示IP地址

spring:
  application:
    name: microservicecloud-dept-consumer